#!/usr/bin/env bash

wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz

tar -xvf gdrive_2.1.1_linux_386.tar.gz

rm gdrive_2.1.1_linux_386.tar.gz

sudo mv gdrive /usr/bin/

sudo mv drive /usr/bin/


